# Generated by Django 4.1.3 on 2022-11-17 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('user_name', models.CharField(max_length=255)),
                ('phone_number', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('watch_hours', models.IntegerField()),
                ('employee_id', models.IntegerField()),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
