# Generated by Django 4.1.3 on 2022-11-17 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_user_delete_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_id', models.IntegerField()),
                ('validity', models.DateField()),
                ('price', models.IntegerField()),
                ('devices_connected', models.IntegerField()),
                ('user_id', models.IntegerField()),
            ],
            options={
                'db_table': 'Subscribers',
            },
        ),
    ]
