# Generated by Django 4.1.3 on 2022-11-19 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_remove_administrator_id_remove_employee_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribers',
            name='id',
        ),
        migrations.AlterField(
            model_name='subscribers',
            name='subscription_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255),
        ),
    ]
