# Generated by Django 4.1.3 on 2022-11-19 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_remove_subscribers_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('content_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_ratings', models.IntegerField()),
                ('year_release', models.IntegerField()),
                ('critics_rating', models.IntegerField()),
                ('content_name', models.CharField(max_length=255)),
                ('employee_id', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, to='database.employee')),
            ],
            options={
                'db_table': 'Content',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_id', models.IntegerField()),
                ('lang_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Genre',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_id', models.IntegerField()),
                ('lang_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Language',
            },
        ),
        migrations.CreateModel(
            name='Show_type',
            fields=[
                ('show_id', models.IntegerField(primary_key=True, serialize=False)),
                ('show_name', models.CharField(max_length=255)),
                ('content_id', models.ForeignKey(db_column='content_id', on_delete=django.db.models.deletion.CASCADE, to='database.content')),
            ],
            options={
                'db_table': 'Show_type',
            },
        ),
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('revenue_id', models.IntegerField(primary_key=True, serialize=False)),
                ('cost', models.IntegerField()),
                ('budget', models.IntegerField()),
                ('content_id', models.ForeignKey(db_column='content_id', on_delete=django.db.models.deletion.CASCADE, to='database.content')),
            ],
            options={
                'db_table': 'Revenue',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('rating_id', models.IntegerField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField()),
                ('content_id', models.ForeignKey(db_column='content_id', on_delete=django.db.models.deletion.CASCADE, to='database.content')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='database.user')),
            ],
            options={
                'db_table': 'Rating',
            },
        ),
        migrations.CreateModel(
            name='Production_House',
            fields=[
                ('production_id', models.IntegerField(primary_key=True, serialize=False)),
                ('production_house', models.CharField(max_length=255)),
                ('revenue', models.IntegerField()),
                ('content_id', models.ForeignKey(db_column='content_id', on_delete=django.db.models.deletion.CASCADE, to='database.content')),
            ],
            options={
                'db_table': 'Production_house',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedback_id', models.IntegerField(primary_key=True, serialize=False)),
                ('platform_rating', models.IntegerField()),
                ('ads_rating', models.IntegerField()),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='database.user')),
            ],
            options={
                'db_table': 'Feedback',
            },
        ),
    ]
