# Generated by Django 4.1.3 on 2022-11-19 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_content_genre_language_show_type_revenue_rating_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Production_House',
        ),
    ]
