# Generated by Django 4.1.3 on 2022-11-19 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0011_delete_production_house'),
    ]

    operations = [
        migrations.CreateModel(
            name='Production_House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_id', models.IntegerField()),
                ('production_house', models.CharField(max_length=255)),
                ('revenue', models.IntegerField()),
                ('content_id', models.IntegerField()),
            ],
            options={
                'db_table': 'Production_house',
            },
        ),
    ]
