# Generated by Django 4.1.3 on 2022-11-19 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0012_production_house'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Show_type',
        ),
    ]
