# Generated by Django 4.1.3 on 2022-11-19 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0013_delete_show_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Show_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_id', models.IntegerField()),
                ('show_name', models.CharField(max_length=255)),
                ('content_id', models.ForeignKey(db_column='content_id', on_delete=django.db.models.deletion.CASCADE, to='database.content')),
            ],
            options={
                'db_table': 'Show_type',
            },
        ),
    ]
